### ISSUE TITLE
Sunucu açılırken hata alıyorum

### ISSUE THREAD

**Issue by portlek** [okyanus-mc/loader#2]
```
https://maven.fabricmc.net/net/fabricmc/tiny-mappings-parser/0.1.1.8/tiny-mappings-parser-0.1.1.8.jar => net.fabricmc.tiny-mappings-parser.0.1.1.8
https://maven.fabricmc.net/net/fabricmc/sponge-mixin/0.7.11.36/sponge-mixin-0.7.11.36.jar => net.fabricmc.sponge-mixin.0.7.11.36
https://maven.fabricmc.net/net/fabricmc/tiny-remapper/0.1.0.33/tiny-remapper-0.1.0.33.jar => net.fabricmc.tiny-remapper.0.1.0.33
https://maven.fabricmc.net/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar => net.fabricmc.fabric-loader-sat4j.2.3.5.4
https://maven.fabricmc.net/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar => com.google.jimfs.jimfs.1.1
https://maven.fabricmc.net/org/ow2/asm/asm/7.1/asm-7.1.jar => org.ow2.asm.asm.7.1
https://maven.fabricmc.net/org/ow2/asm/asm-analysis/7.1/asm-analysis-7.1.jar => org.ow2.asm.asm-analysis.7.1
https://maven.fabricmc.net/org/ow2/asm/asm-commons/7.1/asm-commons-7.1.jar => org.ow2.asm.asm-commons.7.1
https://maven.fabricmc.net/org/ow2/asm/asm-tree/7.1/asm-tree-7.1.jar => org.ow2.asm.asm-tree.7.1
https://maven.fabricmc.net/org/ow2/asm/asm-util/7.1/asm-util-7.1.jar => org.ow2.asm.asm-util.7.1
https://maven.fabricmc.net/com/google/guava/guava/21.0/guava-21.0.jar => com.google.guava.guava.21.0
https://maven.fabricmc.net/net/fabricmc/intermediary/1.14.3/intermediary-1.14.3.jar => intermediary
Patching current jar...
Applying library .okyanus\libraries\com.google.guava.guava.21.0
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:64)
Caused by: java.lang.IllegalArgumentException
        at jdk.zipfs/jdk.nio.zipfs.ZipPath.relativize(ZipPath.java:230)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.lambda$copyDir$0(FabricServerLauncher.java:221)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:502)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.copyDir(FabricServerLauncher.java:218)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.checkLibraries(FabricServerLauncher.java:199)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:61)
```

sorun;
FabricServerLauncher class'ının 221. satırında ki;
`Files.copy(path, to.relativize(path), StandardCopyOption.REPLACE_EXISTING);`
methodundan kaynaklı

**Comment by Admicos** [comment]
Kısa bir araştırma yaptım, JDK 9+ kullanıyorsun sanırım, JDK 8 ile deneyebilir misin?
Tabi gerçekten düzeltmek de gerekecektir, ama şimdilik geçici bir çözüm bulabilirsek güzel olur

**Comment by portlek** [comment]
hm, okey, bi 8 kurayım ben

**Comment by portlek** [comment]
8 i kurup denedim, apply yapıyor tüm patch'leri ancak ondan sonra;
```
Applying library .okyanus\libraries\com.google.guava.guava.21.0
Applying library .okyanus\libraries\com.google.jimfs.jimfs.1.1
Applying library .okyanus\libraries\intermediary
Applying library .okyanus\libraries\net.fabricmc.fabric-loader-sat4j.2.3.5.4
Applying library .okyanus\libraries\net.fabricmc.sponge-mixin.0.7.11.36
Applying library .okyanus\libraries\net.fabricmc.tiny-mappings-parser.0.1.1.8
Applying library .okyanus\libraries\net.fabricmc.tiny-remapper.0.1.0.33
Applying library .okyanus\libraries\org.ow2.asm.asm-analysis.7.1
Applying library .okyanus\libraries\org.ow2.asm.asm-commons.7.1
Applying library .okyanus\libraries\org.ow2.asm.asm-tree.7.1
Applying library .okyanus\libraries\org.ow2.asm.asm-util.7.1
Applying library .okyanus\libraries\org.ow2.asm.asm.7.1
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:64)
Caused by: java.lang.RuntimeException: java.nio.file.FileSystemException: D:\okyanus\okyanus-1.14.3-0.1.0.jar: Dosya başka bir işlem tarafından kullanıldığından bu işlem dosyaya erişemiyor.

        at net.fabricmc.loader.launch.server.FabricServerLauncher.checkLibraries(FabricServerLauncher.java:209)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:61)
Caused by: java.nio.file.FileSystemException: D:\okyanus\okyanus-1.14.3-0.1.0.jar: Dosya başka bir işlem tarafından kullanıldığından bu işlem dosyaya erişemiyor.

        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
        at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
        at java.nio.file.Files.delete(Files.java:1126)
        at com.sun.nio.zipfs.ZipFileSystem.sync(ZipFileSystem.java:1294)
        at com.sun.nio.zipfs.ZipFileSystem.close(ZipFileSystem.java:277)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.checkLibraries(FabricServerLauncher.java:208)
        ... 1 more
```
bu hatayı veriyor, yönetici olarak vs. çalıştırmayı denedim

**Comment by Admicos** [comment]
```Caused by: java.lang.RuntimeException: java.nio.file.FileSystemException: D:\okyanus\okyanus-1.14.3-0.1.0.jar: Dosya başka bir işlem tarafından kullanıldığından bu işlem dosyaya erişemiyor.```

Windowsda hiç denemedim bu kurucuyu, belki kendisini okumak için açtığından yazamıyor olabilir, bilmiyorum, daha detaylı bakmam gerekecek bu duruma.

**Comment by Admicos** [comment]
Şu anki jar yöntemi zaten acayip kötü kodlanmış bir halde. Acaba direkt "server jarı" olmaya çalışmayı bırakıp kendimize installer mı yapsak? Ki o zaman da Fabric Loader'ı forklamaya gerek kalmazı ki :p

**Comment by portlek** [comment]
aslına bakarsan, bir çok(belki de hepsi) sunucu türleri, jar'ları çalıştırarak yapıyor, installer yapıp güzel bir arayüze sahip program yapılabilir, kullanışlı ve kullanıcı dostu olur. öyle yapması daha iyi olur sanırım.
- BukkitGUI
gibi

**Comment by Admicos** [comment]
Aslında, direkt Fabric'e bırakalım mod yüklemeyi. `Mod` interface'ini Fabric'in `DedicatedServerModInitializer`i, `okyanus.json`'u `fabric.mod.json`'a değiştirsek zaten Fabric loader yüklüyor otomatik olarak. Bizim "Okyanus Loader" da Fabric için bir tür gui falan olur.

**Comment by portlek** [comment]
öyle yapmak daha orjinal olucaktır, o şekilde yapabiliriz.

**Comment by portlek** [comment]
Mod interface'İni açıkcası sevmedim, çünkü bir çok instance kullanmak gerektiriyor, class olması daha iyi olur, DI kullanmak adına, geliştiricilerin her şeyi ordan çekmesi daha sağlıklı ve anlaşılır olucaktır, bu şekilde her seferinde instance çağırmak ya da neyin nerde olduğunu sürekli hatırlamak zorunda kalmazlar, `extends Mod` yapmaları tüm geliştirme araçlarına erişimine açması gayet kullanışlı ve basit olur diye düşünüyorum, kodlaması da ayrıca kolay olucaktır.

**Comment by Admicos** [comment]
Acaba bizim class'ımız DedicatedServerModInitializer implementlese Fabric hala yükler mi, bi Discordlarına sorayım

**Comment by portlek** [comment]
bence yükler, çünkü senin açtığın mod interface'İn ile zaten bunu yapıyorsun, sen interface açmışsın extra olarak abstract class açmakla aynı şey aslında;
```java
public final class EntrypointServer {
	public static void start(File runDir, Object gameInstance) {
		if (runDir == null) {
			runDir = new File(".");
		}

		FabricLoader.INSTANCE.instantiateMods(runDir, gameInstance);
		EntrypointUtils.logErrors("main", FabricLoader.INSTANCE.getEntrypoints("main", ModInitializer.class), ModInitializer::onInitialize);
		EntrypointUtils.logErrors("server", FabricLoader.INSTANCE.getEntrypoints("server", DedicatedServerModInitializer.class), DedicatedServerModInitializer::onInitializeServer);
		EntrypointUtils.logErrors("okyanus", FabricLoader.INSTANCE.getEntrypoints("server", Mod.class), Mod::init);
	}
}
```
buraya sadece mod.class ı silip direk DedicatedServerModİnitializer ı bırakıcaz ve api projesinde abstract class açıcaz, sanırım bu şekilde olucak

**Comment by Admicos** [comment]
```
[23:10] UpcraftLP: ok so:
a child class would get loaded (since it would indirectly inherit from DedicatedServerInitializer), IF (and only if) it was listed in the fabric.mod.json's entry points.
```
fabric.mod.json'da entrypointlere koyduğumuz ve extendleyecekleri classımızın DedicatedServerModInitializer'ı implement ettiğine emin olduğumuz sürece, mod yüklenir diye duydum.

Oradaki classları düzenlersek forkumuzu kullanmak gerekir, ki normal Fabric kullanmak  daha mantıklı geliyor şimdi.

**Comment by portlek** [comment]
```java
package club.issizler.okyanus.api;

import java.util.logging.Logger;

public abstract class Mod implements DedicatedServerModInitializer {

    protected final CommandRegisty commandRegisty = new commandregisty();
    protected final EventRegisty eventRegisty = new eventRegistry();
    // Diğer tüm geliştirici araçları vs.
    protected final Logger logger = Logger.getLogger("Okyanus");

    public abstract void enable();
    public abstract void disable();

}

```
bu tür bir şeyden bahsediyorum tam olarak

**Comment by Admicos** [comment]
Aynen!

```java
package com.a;

public class MySuperMod extends Mod {
....
}```

yaptıktan sonra, fabric.mod.json'daki `entrypoints.server` listesine`com.a.MySuperMod` koyarsan çalışacak diyorlar, test etmemiz gerekebilir.

**Comment by Admicos** [comment]
Ben mod template'indeki Okyanus referanslarını Fabric'e çevirmeye geçiyorum, Loader yerine bir şey buluruz yavaştan.

Bu issue'yu kapatıyorum artık, http://fabricmc.net/use/ adresinden onların installerini indirebilirsin gerekirse.

Bu yeni API hakkında api'ye yeni issue açmak gerekebilir.

**Comment by Admicos** [comment]
Fabric Discord'undan aldığım bir bilgiye göre, direkt olarak metod referansı verebiliyormuşuz entrypoints'de. İşimize yarayabilir belki.
